syntax = "proto3";
import "google/protobuf/timestamp.proto";
package legacy;

// 服务定义
service LegacyVisionService {
  // RPC 1: 加载视觉方案
  rpc LoadSolution (LoadSolutionRequest) returns (LoadSolutionResponse);

  // RPC 2: 处理本地图像文件 
  rpc ProcessImageFromPathStreamed(ProcessImageFromPathRequest) returns (stream StreamedProcessImageResponse);

  // RPC 3: 处理从客户端发送的图像字节数据
  rpc ProcessImageFromBytesStreamed(ProcessImageFromBytesRequest) returns (stream StreamedProcessImageResponse);

}

// ===================================================================
// 消息定义
// ===================================================================

// 用于处理图像字节数据的请求
message ProcessImageFromBytesRequest {
  bytes image_data = 1;      // 图像的原始字节数据 (例如 BMP 格式)
  string operation_id = 2;   // 操作ID
}


message Point2D {
  float x = 1;
  float y = 2;
}

message LoadSolutionRequest {
  string solution_name = 1;
}

message LoadSolutionResponse {
  bool success = 1;
  string message = 2;
}

message ProcessImageFromPathRequest {
  string image_path = 1;
  string operation_id = 2;
}

message ProcessImageMetadata {
  bool success = 1;
  string message = 2;
  google.protobuf.Timestamp timestamp = 3;
  string operation_id = 4;
  repeated Point2D corner_points = 5;
  string source_image_path = 7;
  double process_time_seconds = 8;
}

message ImageChunk {
  bytes data = 1;
}

message StreamedProcessImageResponse {
  oneof content {
    ProcessImageMetadata metadata = 1;
    ImageChunk chunk = 2;
  }
}
